site_name: BYU CE 544
site_url: https://ce544.readthedocs.io/en/latest/
site_description: Course materials for CE 544 at BYU
site_author: Norm Jones (instructor) and TAs of CE 544 at BYU
repo_url: https://github.com/cce544/
favicon: 'images/favicon.ico'
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js
  - js/mathjax-config.js
markdown_extensions:
    - attr_list
    - sane_lists
    - md_in_html
    - admonition
    - pymdownx.arithmatex:
        generic: true
theme: readthedocs
extra_css:
  - css/custom.css
nav:
  - Home: index.md
  - Class Resources:
    - Syllabus: resources/syllabus.md
    - Case Study: resources/casestudy.md
    - GMS Software: resources/gms.md
    - UTEXASED: resources/utexased/installation.md
    - Textbook: resources/textbook.md
    - Course Overview: resources/overview/intro_read.md
  - Unit 1 - Seepage Analysis:
    - Hydraulic Head Concepts:
        - Pre-Class: unit1/01_head/head_read.md
        - In-Class: unit1/01_head/head_class.md
        - Homework: unit1/01_head/head_hw.md
    - Darcy's Law:
        - Pre-Class: unit1/02_darcy/darcy_read.md
        - In-Class: unit1/02_darcy/darcy_class.md
        - Homework: unit1/02_darcy/darcy_hw.md
    - Governing Equations:
        - Pre-Class (Darcy 2D): unit1/03_darcy_2d/darcy_2d_read.md
        - Pre-Class (Gov Eqs): unit1/04_goveqs/goveqs_read.md
        - In-Class: unit1/03_darcy_2d/darcy_2d_class.md
    - Flow Nets:
        - Pre-Class: unit1/05_flownets/flow_read.md
        - In-Class: unit1/05_flownets/flow_class.md
        - Homework: unit1/05_flownets/flow_hw.md
    - Analytical Solutions:
        - Pre-Class: unit1/06_analytical/analytical_read.md
        - In-Class: unit1/06_analytical/analytical_class.md
        - Homework: unit1/06_analytical/analytical_hw.md
    - Well Equations:
        - Pre-Class: unit1/07_wells/wells_read.md
        - In-Class: unit1/07_wells/wells_class.md
        - Homework: unit1/07_wells/wells_hw.md
    - Construction Dewatering:
        - Pre-Class: unit1/08_dewatering/dewatering_read.md
        - In-Class: unit1/08_dewatering/dewatering_class.md
        - Homework: unit1/08_dewatering/dewatering_hw.md
    - Finite Difference Method:
        - Pre-Class 1: unit1/09_findiff/findiff_read1.md
        - Pre-Class 2: unit1/09_findiff/findiff_read2.md
        - In-Class 1: unit1/09_findiff/findiff_class1.md
        - In-Class 2: unit1/09_findiff/findiff_class2.md
        - Homework 1: unit1/09_findiff/findiff_hw1.md
        - Homework 2: unit1/09_findiff/findiff_hw2.md
    - Finite Element Seepage Analysis:
        - Pre-Class 1: unit1/10_seepage/seep_read1.md
        - Pre-Class 2: unit1/10_seepage/seep_read2.md
        - In-Class 1: unit1/10_seepage/seep_class1.md
        - In-Class 2: unit1/10_seepage/seep_class2.md
        - In-Class 3: unit1/10_seepage/seep_class3.md
        - Homework 1: unit1/10_seepage/seep_hw1.md
        - Homework 2: unit1/10_seepage/seep_hw2.md
  - Unit 2 - Slope Stability:
    - Causes of Slope Failure:
        - Pre-Class: unit2/01_causes/causes_read.md
    - Shear Strength Concepts:
        - Pre-Class: unit2/02_shear/shear_read.md
        - Homework: unit2/02_shear/shear_hw.md
    - Limit Equilibrium Method - Part 1 :
        - Pre-Class: unit2/03_limiteq1/limiteq1_read.md
        - In-Class: unit2/03_limiteq1/limiteq1_class.md
        - Homework: unit2/03_limiteq1/limiteq1_hw.md
    - Limit Equilibrium Method - Part 2:
        - Pre-Class: unit2/04_limiteq2/limiteq2_read.md
        - In-Class: unit2/04_limiteq2/limiteq2_class.md
        - Homework: unit2/04_limiteq2/limiteq2_hw.md
    - XSLOPE - Slope Stability Analysis:
        - Pre-Class: unit2/05_xlope/utexased_read.md
        - In-Class 1: unit2/05_xlope/utexased_class1.md
        - In-Class 2: unit2/05_xlope/utexased_class2.md
        - Homework 1: unit2/05_xlope/utexased_hw1.md
        - Homework 2: unit2/05_xlope/utexased_hw2.md
    - Reinforced Slopes:
        - Pre-Class: unit2/06_reinforced/reinforced_read.md
        - In-Class: unit2/06_reinforced/reinforced_class.md
        - Homework: unit2/06_reinforced/reinforced_hw.md
    - Rapid Drawdown Analysis:
        - Pre-Class: unit2/07_rapid/rapid_read.md
        - Homework: unit2/07_rapid/rapid_hw.md
    - Seepage/Slope Stability Integration:
        - Pre-Class: unit2/08_seep_slope/seep_slope_read.md
        - In-Class: unit2/08_seep_slope/seep_slope_classs.md
        - Homework: unit2/08_seep_slope/seep_slope_hw.md
    - Seismic Slope Stability:
        - Pre-Class: unit2/09_seismic/seismic_read.md
        - In-Class: unit2/09_seismic/seismic_class.md
        - Homework: unit2/09_seismic/seismic_hw.md
    - Important Details of Stability Analysis:
        - Pre-Class: unit2/10_details/details_read.md
        - In-Class: unit2/10_details/details_class.md
        - Homework: unit2/10_details/details_hw.md
    - Reliability Analysis:
        - Pre-Class: unit2/11_reliability/reliability_read.md
        - In-Class: unit2/11_reliability/reliability_class.md
        - Homework: unit2/11_reliability/reliability_hw.md
    - FE Slope Stability Analysis:
        - Pre-Class: unit2/12_fem/fem_read.md
        - In-Class: unit2/12_fem/fem_class.m
        - Homework: unit2/12_fem/fem_hw.m